services:
  client:
    image: v2net/messagehub-element
    build:
      dockerfile: Automation/Docker/element.Dockerfile
    ports:
      - "127.84.48.1:80:80/tcp"
  server:
    image: v2net/messagehub
    build:
      dockerfile: Automation/Docker/Dockerfile
    network_mode: "host"
    volumes:
      - data:/root/app/Data
      - content:/root/app/Content
volumes:
  data:
  content:
