services:
  element:
    image: v2net/messagehub-element
    build:
      dockerfile: Automation/Docker/ElementServer.Dockerfile
    network_mode: "host"
  server:
    image: v2net/messagehub
    build:
      dockerfile: Automation/Docker/Dockerfile
    network_mode: "host"
    volumes:
      - data:/root/app/Data
      - content:/root/app/Content
volumes:
  data:
  content:
